version: "3"

services:
  app:
    build: .
    container_name: codeflix-subscribers-app
    command: /bin/sh -c 'pip install -r requirements.txt && python manage.py runserver 0.0.0.0:8000'
    volumes:
      - .:/home/python/app
    ports:
      - "8000:8000"
