version: "3"

services:
  app:
    build: .
    container_name: codeflix-subscribers-app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
